name: share_plus_example
description: Demonstrates how to use the share_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  share_plus:
    git:
      url: "https://gitee.com/hxy-111/flutter_plus_plugins.git"
      path: "packages/share_plus/share_plus"
  image_picker:
    git:
      url: "https://gitee.com/hxy-111/flutter_packages.git"
      path: "packages/image_picker/image_picker"
  file_selector:
    git:
      url: "https://gitee.com/hxy-111/flutter_packages.git"
      path: "packages/file_selector/file_selector"
  path_provider:
    git:
      url: "https://gitee.com/hxy-111/flutter_packages.git"
      path: "packages/path_provider/path_provider"

dependency_overrides:
  path_provider:
    git:
      url: "https://gitee.com/hxy-111/flutter_packages.git"
      path: "packages/path_provider/path_provider"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/flutter_logo.png

environment:
  sdk: '>=2.18.0 <4.0.0'
