name: device_info_plus_example
description: Demonstrates how to use the device_info_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  device_info_plus:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"
